In [1]:
#import the libraries
import pandas as pd
import numpy as np
import scipy
from scipy import stats
from scipy.stats import norm

In [2]:
# Load the dataset
data=pd.read_csv('E:\Assignment\Assignment 3 - Hypothesis testing\CostomerOrderForm.csv')
data.head()

  Phillippines   Indonesia       Malta       India
0   Error Free  Error Free   Defective  Error Free
1   Error Free  Error Free  Error Free   Defective
2   Error Free   Defective   Defective  Error Free
3   Error Free  Error Free  Error Free  Error Free
4   Error Free  Error Free   Defective  Error Free

In [3]:
data.describe()

       Phillippines   Indonesia       Malta       India
count           300         300         300         300
unique            2           2           2           2
top      Error Free  Error Free  Error Free  Error Free
freq            271         267         269         280

In [4]:
Phillippines_value=data['Phillippines'].value_counts()
Indonesia_value=data['Indonesia'].value_counts()
Malta_value=data['Malta'].value_counts()
India_value=data['India'].value_counts()
print(Phillippines_value)
print(Indonesia_value)
print(Malta_value)
print(India_value)

Error Free    271
Defective      29
Name: Phillippines, dtype: int64
Error Free    267
Defective      33
Name: Indonesia, dtype: int64
Error Free    269
Defective      31
Name: Malta, dtype: int64
Error Free    280
Defective      20
Name: India, dtype: int64

In [5]:
alpha=0.05
errorfree = [271,267,269,280]
defective=[29,33,31,20]
count=[errorfree, defective]
print(count)

[[271, 267, 269, 280], [29, 33, 31, 20]]

In [12]:
chiStats = scipy.stats.chi2_contingency(count)
Chi_pValue=chiStats[1]
print("p-value is: "+str(Chi_pValue))
print('Interpret by p-Value')
if chiStats[1] < 0.05:
  print('we reject null hypothesis')
else:
  print('we accept null hypothesis')

p-value is: 0.2771020991233135
Interpret by p-Value
we accept null hypothesis