## Salary Data

In [1]:
#Importing the libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import confusion_matrix
from sklearn import preprocessing

In [2]:
#Importing data
salary_train = pd.read_csv('E:\Assignment\Assignment 12 - Naive bayes\SalaryData_Train.csv')
salary_test = pd.read_csv('E:\Assignment\Assignment 12 - Naive bayes\SalaryData_Test.csv')

In [3]:
salary_train.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [4]:
salary_test.head()

,age,workclass,education,educationno,maritalstatus,occupation,relationship,race,sex,capitalgain,capitalloss,hoursperweek,native,Salary
0,25,Private,11th,7,Never-married,Machine-op-inspct,Own-child,Black,Male,0,0,40,United-States,<=50K
1,38,Private,HS-grad,9,Married-civ-spouse,Farming-fishing,Husband,White,Male,0,0,50,United-States,<=50K
2,28,Local-gov,Assoc-acdm,12,Married-civ-spouse,Protective-serv,Husband,White,Male,0,0,40,United-States,>50K
3,44,Private,Some-college,10,Married-civ-spouse,Machine-op-inspct,Husband,Black,Male,7688,0,40,United-States,>50K
4,34,Private,10th,6,Never-married,Other-service,Not-in-family,White,Male,0,0,30,United-States,<=50K

In [5]:
#Preprocessing
from sklearn import preprocessing
number = preprocessing.LabelEncoder()

In [6]:
string_columns=["workclass","education","maritalstatus","occupation","relationship","race","sex","native"]
for i in string_columns:
    salary_train[i] = number.fit_transform(salary_train[i])
    salary_test[i] = number.fit_transform(salary_test[i])

In [7]:
colnames = salary_train.columns
colnames

Index(['age', 'workclass', 'education', 'educationno', 'maritalstatus',
       'occupation', 'relationship', 'race', 'sex', 'capitalgain',
       'capitalloss', 'hoursperweek', 'native', 'Salary'],
      dtype='object')

In [8]:
len(colnames[0:13])

13

In [9]:
# Splitting data into train and test
trainX = salary_train[colnames[0:13]]
trainY = salary_train[colnames[13]]
testX  = salary_test[colnames[0:13]]
testY  = salary_test[colnames[13]]

# Gaussian

In [10]:
gnb = GaussianNB()

In [11]:
# Building Model
build_gnb = gnb.fit(trainX,trainY)

In [12]:
# Predicting Model
pred_gnb= build_gnb.predict(testX)

In [13]:
# Confusion matrix GaussianNB model
confusion_matrix(testY,pred_gnb)

array([[10759,   601],
       [ 2491,  1209]], dtype=int64)

In [14]:
print ("Accuracy",(10759+1209)/(10759+601+2491+1209))

Accuracy 0.7946879150066402

In [15]:
# In Gaussian classifier we are obtaining Accuracy nearly 80%

# Multinomial

In [16]:
mnb = MultinomialNB()

In [17]:
# Building Model
build_mnb = gnb.fit(trainX,trainY)

In [18]:
# Predicting Model
pred_mnb= build_mnb.predict(testX)

In [19]:
# Confusion matrix MultinominalNB model
confusion_matrix(testY,pred_mnb)

array([[10759,   601],
       [ 2491,  1209]], dtype=int64)

In [20]:
print("Accuracy",(10891+780)/(10891+780+2920+780))

Accuracy 0.7592869689675362

In [21]:
# In Multinominal classifier we are obtaining Accuracy nearly 76%